name: CMake

on:
  push:
    branches: [ main ]
    tags: '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: seanmiddleditch/gha-setup-ninja@master
    
      # use apt to download gcc & g++ 10
    - run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10
      shell: bash
    
    - name: Configure CMake
      run:    cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      shell:  bash
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
            
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: seanmiddleditch/gha-setup-ninja@master
    
      # use apt to download gcc & g++ 10
    - run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10
      shell: bash
        
    - name: Configure CMake
      run:    cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      env:
        CC:   gcc-10
        CXX:  g++-10
      
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
            

