name: Create Release

on:
  workflow_run:
    workflows:
      - Linux Build
    types: completed
  workflow_dispatch:
    inputs:
      name:
        description:  'Release Name'
        required:     true
        type:         string
      tag: # Target tag to make a release for
        description:  'Release Tag'
        required:     true
        type:         string
      is-draft: # Input that selects whether to make a draft release or a public release
        description:  'Make Draft Release'
        required:     false
        default:      'true'
        type:         boolean
      is-prerelease: # Input that selects whether to make a pre-release or normal release
        description:  'Make Pre-Release'
        required:     false
        default:      'false'
        type:         boolean
      autogenerate:
        description:  'Autogenerate Release Notes From Commits'
        required:     false
        default:      'false'
        type:         boolean
      body:
        description:  'Release Body Paragraph'
        required:     false
        default:      ''
        

jobs:    
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    
    steps:
    - name: Wait for build workflows to complete
      if:   ${{ github.event_name != 'workflow_dispatch' }}
      uses: lewagon/wait-on-check-action@v1.1.1
      with:
        ref: ${{github.sha}}
        repo-token: ${{secrets.GITHUB_TOKEN}}
        running-workflow-name: 'Create Release'
        allowed-conclusions: success
        wait-interval: 15
    
    - name: Download Latest Artifact for Linux
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow:             Linux.yml
        workflow_conclusion:  success
        
    - name: Download Latest Artifact for Windows
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow:             Windows.yml
        workflow_conclusion:  success
        
    - name: Download Latest Artifact for macOS
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow:             macOS.yml
        workflow_conclusion:  success
        
    - name: Compile Artifacts
      run:  mv ./latest-*/* ./
    
    - name: Create Release (workflow_dispatch)
      if:   ${{ github.event_name == 'workflow_run' }}
      uses: softprops/action-gh-release@v1
      with:
        draft:                    ${{github.event.inputs.is-draft}}
        prerelease:               ${{github.event.inputs.is-prerelease}}
        tag_name:                 ${{github.event.inputs.tag}}
        name:                     ${{github.event.inputs.name}}
        generate_release_notes:   ${{github.event.inputs.autogenerate}}
        body:                     ${{github.event.inputs.body}}
        fail_on_unmatched_files:  true
        files:                    ./*.zip

    - name: Get Latest Tag (workflow_run)
      id: latest-tag
      if:   ${{ github.event_name == 'workflow_run' }}
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback:                 0.0.0

    - name: Create Draft Release (workflow_run)
      if:   ${{ github.event_name == 'workflow_run' }}
      uses: softprops/action-gh-release@v1
      with:
        draft:                    true
        prerelease:               false
        tag_name:                 ${{ steps.latest-tag.outputs.tag }}
        name:                     '${{steps.latest-tag.outputs.tag}} Release'
        generate_release_notes:   false
        body:                     ''
        fail_on_unmatched_files:  true
        files:                    ./*.zip

