name: Linux Build

on:
  push:
    branches: [ main ]
    tags: '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: seanmiddleditch/gha-setup-ninja@master
    
      # use apt to download gcc & g++ 10
    - run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10 zip
      shell: bash
    
    - name: Configure CMake
      run:    cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      shell:  bash
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Get Self-Reported Version Number
      uses: mathiasvr/command-output@v1
      id: getver
      with:
        run:  |
              ${{github.workspace}}/build/${{env.BUILD_TYPE}}/ARRCON -vq
              
    - name: Echo Version Number
      run:  |
            echo "${{steps.getver.outputs.stdout}}"
      
    - name: Compress Executable & Label Archive
      run:  |
            zip -T9 ${{github.workspace}}/build/${{env.BUILD_TYPE}}/ARRCON ARRCON-${{steps.getver.outputs.stdout}}-macOS.zip
      shell: bash
      
    - name: Upload Archive as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{steps.getver.outputs.stdout}}-macOS
        path: ./*.zip
        retention-days: 2



