name: Create Release

on:
  workflow_dispatch:
    inputs:
      is-draft:
        description: 'Is Draft'
        type: boolean
        required: true
      tag:
        description: 'Target Tag'
        required: true
      notes:
        description: 'Release Notes'
        default: ''
        required: true
      is-prerelease:
        description: 'Is Pre-Release'
        type: boolean
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      # Get the latest linux release artifact
    - name: Download Latest Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: latest-linux
        path: ${{github.workspace}}
      # Get the latest windows release artifact
    - name: Download Latest Windows Artifact
      uses: actions/download-artifact@v2
      with:
        name: latest-windows
        path: ${{github.workspace}}
      # Get the latest macos release artifact
    - name: Download Latest macOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: latest-macos
        path: ${{github.workspace}}
        
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: ${{github.event.inputs.is-draft}}
        body: ${{github.event.inputs.notes}}
        files:  |
                ARRCON-${{github.event.inputs.tag}}-Linux.zip
                ARRCON-${{github.event.inputs.tag}}-Windows.zip
                ARRCON-${{github.event.inputs.tag}}-macOS.zip



